# Generated by Django 5.2.7 on 2025-11-13 12:59

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nume', models.CharField(max_length=255)),
                ('prenume', models.CharField(max_length=255)),
                ('biografie', models.TextField()),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nume', models.CharField(max_length=255)),
                ('descriere', models.TextField(null=True)),
                ('data_actualizarii', models.DateTimeField()),
                ('culoare', models.CharField(default='#37827c', max_length=20)),
                ('icon', models.CharField(default='fa-tag', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editura',
            fields=[
                ('id_editura', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nume_editura', models.CharField(max_length=255)),
                ('website', models.URLField(unique=True)),
                ('adresa', models.CharField(max_length=500)),
                ('mail', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('detalii', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorie',
            fields=[
                ('id_subcategorie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nume', models.CharField(max_length=200)),
                ('popularitate', models.PositiveIntegerField()),
                ('descriere', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefon', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nasterii', models.DateField(blank=True, null=True)),
                ('adresa', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carte',
            fields=[
                ('id_carte', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('titlu', models.CharField(max_length=255)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descriere', models.TextField()),
                ('data_publicarii', models.DateField(default=datetime.datetime(2025, 11, 13, 14, 59, 51, 86184))),
                ('limba', models.CharField(choices=[('optiune1', 'romana'), ('optiune2', 'engleza'), ('optiune3', 'franceza'), ('optiune4', 'japoneza'), ('optiune5', 'coreana')], max_length=100)),
                ('format', models.CharField(default='PDF', max_length=255)),
                ('spatiu_descarcare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('in_stoc', models.BooleanField()),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='carti/')),
                ('autor', models.ManyToManyField(to='app_eBooks.autor')),
                ('categorii', models.ManyToManyField(blank=True, to='app_eBooks.categorie')),
                ('id_editura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eBooks.editura')),
                ('oferte', models.ManyToManyField(blank=True, to='app_eBooks.oferta')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='subcategorii',
            field=models.ManyToManyField(blank=True, to='app_eBooks.subcategorie'),
        ),
    ]
