# Generated by Django 5.2.7 on 2025-11-27 12:37

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eBooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oferta',
            name='categorii',
            field=models.ManyToManyField(related_name='oferte', to='app_eBooks.categorie'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='nume',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='data_publicarii',
            field=models.DateField(default=datetime.datetime(2025, 11, 27, 14, 37, 38, 460262)),
        ),
        migrations.CreateModel(
            name='Vizualizari',
            fields=[
                ('id_vizualizare', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data_vizualizare', models.DateTimeField(auto_now_add=True)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_eBooks.carte')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
