# Generated by Django 5.2.7 on 2025-12-03 13:24

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eBooks', '0002_myuser_cod_myuser_email_confirmat_oferta_categorii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='utilizatori',
            field=models.ManyToManyField(blank=True, related_name='oferte_primite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carte',
            name='data_publicarii',
            field=models.DateField(default=datetime.datetime(2025, 12, 3, 15, 24, 1, 451681)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 3, 15, 24, 1, 451681)),
        ),
    ]
