# Generated by Django 5.2.7 on 2025-12-04 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eBooks', '0003_oferta_utilizatori_alter_carte_data_publicarii_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta',
            options={'permissions': [('vizualizeaza_oferta', 'Poate vizualiza oferta specială')]},
        ),
        migrations.AddField(
            model_name='myuser',
            name='blocat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carte',
            name='data_publicarii',
            field=models.DateField(default=datetime.datetime(2025, 12, 4, 11, 17, 42, 662428)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 4, 11, 17, 42, 662428)),
        ),
    ]
