# Generated by Django 5.2.7 on 2025-12-23 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eBooks', '0004_alter_oferta_options_myuser_blocat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carte',
            name='stoc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carte',
            name='data_publicarii',
            field=models.DateField(default=datetime.datetime(2025, 12, 23, 18, 58, 6, 302229)),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='data_actualizarii',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 23, 18, 58, 6, 300222)),
        ),
    ]
