# Generated by Django 5.2.7 on 2025-12-24 01:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eBooks', '0005_carte_stoc_alter_carte_data_publicarii_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='data_publicarii',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 3, 24, 18, 780228)),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 24, 3, 24, 18, 780228)),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produse', models.JSONField()),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
